function main()
    code_original_HHKBLite2 = Dict(
        "KEY_MINUS" => "7002d",
        "KEY_EQUAL" => "7002e",
        "KEY_Q" => "70014",
        "KEY_W" => "7001a",
        "KEY_E" => "70008",
        "KEY_R" => "70015",
        "KEY_T" => "70017",
        "KEY_Y" => "7001c",
        "KEY_U" => "70018",
        "KEY_I" => "7000c",
        "KEY_O" => "70012",
        "KEY_P" => "70013",
        "KEY_LEFTBRACE" => "7002f",
        "KEY_RIGHTBRACE" => "70030",
        "KEY_A" => "70004",
        "KEY_S" => "70016",
        "KEY_D" => "70007",
        "KEY_F" => "70009",
        "KEY_G" => "7000a",
        "KEY_H" => "7000b",
        "KEY_J" => "7000d",
        "KEY_K" => "7000e",
        "KEY_L" => "7000f",
        "KEY_SEMICOLON" => "70033",
        "KEY_APOSTROPHE" => "70034",
        "KEY_Z" => "7001d",
        "KEY_X" => "7001b",
        "KEY_C" => "70006",
        "KEY_V" => "70019",
        "KEY_B" => "70005",
        "KEY_N" => "70011",
        "KEY_M" => "70010",
        "KEY_COMMA" => "70036",
        "KEY_DOT" => "70037",
        "KEY_SLASH" => "70038",
        "KEY_ESC" => "70029",
        "KEY_RIGHTALT" => "700e6",
        "KEY_RIGHTMETA" => "700e7",
    )
    map_dvorak_forward = Dict(
        "KEY_MINUS" => "KEY_LEFTBRACE",
        "KEY_EQUAL" => "KEY_RIGHTBRACE",
        "KEY_Q" => "KEY_APOSTROPHE",
        "KEY_W" => "KEY_COMMA",
        "KEY_E" => "KEY_DOT",
        "KEY_R" => "KEY_P",
        "KEY_T" => "KEY_Y",
        "KEY_Y" => "KEY_F",
        "KEY_U" => "KEY_G",
        "KEY_I" => "KEY_C",
        "KEY_O" => "KEY_R",
        "KEY_P" => "KEY_L",
        "KEY_LEFTBRACE" => "KEY_SLASH",
        "KEY_RIGHTBRACE" => "KEY_EQUAL",
        "KEY_A" => "KEY_A",
        "KEY_S" => "KEY_O",
        "KEY_D" => "KEY_E",
        "KEY_F" => "KEY_U",
        "KEY_G" => "KEY_I",
        "KEY_H" => "KEY_D",
        "KEY_J" => "KEY_H",
        "KEY_K" => "KEY_T",
        "KEY_L" => "KEY_N",
        "KEY_SEMICOLON" => "KEY_S",
        "KEY_APOSTROPHE" => "KEY_MINUS",
        "KEY_Z" => "KEY_SEMICOLON",
        "KEY_X" => "KEY_Q",
        "KEY_C" => "KEY_J",
        "KEY_V" => "KEY_K",
        "KEY_B" => "KEY_X",
        "KEY_N" => "KEY_B",
        "KEY_M" => "KEY_M",
        "KEY_COMMA" => "KEY_W",
        "KEY_DOT" => "KEY_V",
        "KEY_SLASH" => "KEY_Z",
        "KEY_ESC" => "KEY_MUHENKAN",
        "KEY_RIGHTALT" => "KEY_ESC",
        "KEY_RIGHTMETA" => "KEY_RIGHTALT",
    )

    remap(code_original_HHKBLite2, map_dvorak_forward)
end
function remap(code, map)
    for (before, after) in map
        before == after && continue
        println("#$before -> $after")
        println(" KEYBOARD_KEY_" * code[before] * "=" * lowercase(after))
    end
end
main()