struct bzmodes
    raw::String
    ::String
end

tron = Dict(
    "00" => "",
    "01" => "",
    "02" => "",
    "03" => "",
    "04" => "",
    "05" => "",
    "06" => "",
    "07" => "",
    "00" => "",
    "01" => "",
    "02" => "",
    "03" => "",
    "04" => "",
    "05" => "",
    "06" => "",
    "07" => "",
)

tlsplit_raw = Dict(
    "1" => "",
    "2" => "",
    "3" => "",
    "4" => "",
    "5" => "",
    "6" => "",
    "7" => "",
    "8" => "",
    "9" => "",
    "0" => "",
    "minus" => "",
    "hat" => "",
    "yen" => "",
    "Q" => "70014",
    "W" => "7001a",
    "E" => "70008",
    "R" => "70015",
    "T" => "70017",
    "Y" => "7001c",
    "U" => "70018",
    "I" => "7000c",
    "O" => "70012",
    "P" => "70013",
    "at" => "70013",
    "leftbrace" => "7002f",
    "A" => "70004",
    "S" => "70016",
    "D" => "70007",
    "F" => "70009",
    "G" => "7000a",
    "H" => "7000b",
    "J" => "7000d",
    "K" => "7000e",
    "L" => "7000f",
    "semicolon" => "70033",
    "colon" => "70033",
    "rithtbrace" => "70030",
    "Z" => "7001d",
    "X" => "7001b",
    "C" => "70006",
    "V" => "70019",
    "B" => "70005",
    "N" => "70011",
    "M" => "70010",
    "comma" => "70036",
    "period" => "70037",
    "slash" => "70038",
    "ro" => "70029",
)
tlsplit_benizara = Dict(
    "KEY_MINUS" => "KEY_LEFTBRACE",
    "KEY_EQUAL" => "KEY_RIGHTBRACE",
    "KEY_Q" => "KEY_APOSTROPHE",
    "KEY_W" => "KEY_COMMA",
    "KEY_E" => "KEY_DOT",
    "KEY_R" => "KEY_P",
    "KEY_T" => "KEY_Y",
    "KEY_Y" => "KEY_F",
    "KEY_U" => "KEY_G",
    "KEY_I" => "KEY_C",
    "KEY_O" => "KEY_R",
    "KEY_P" => "KEY_L",
    "KEY_LEFTBRACE" => "KEY_SLASH",
    "KEY_RIGHTBRACE" => "KEY_EQUAL",
    "KEY_A" => "KEY_A",
    "KEY_S" => "KEY_O",
    "KEY_D" => "KEY_E",
    "KEY_F" => "KEY_U",
    "KEY_G" => "KEY_I",
    "KEY_H" => "KEY_D",
    "KEY_J" => "KEY_H",
    "KEY_K" => "KEY_T",
    "KEY_L" => "KEY_N",
    "KEY_SEMICOLON" => "KEY_S",
    "KEY_APOSTROPHE" => "KEY_MINUS",
    "KEY_Z" => "KEY_SEMICOLON",
    "KEY_X" => "KEY_Q",
    "KEY_C" => "KEY_J",
    "KEY_V" => "KEY_K",
    "KEY_B" => "KEY_X",
    "KEY_N" => "KEY_B",
    "KEY_M" => "KEY_M",
    "KEY_COMMA" => "KEY_W",
    "KEY_DOT" => "KEY_V",
    "KEY_SLASH" => "KEY_Z",
    "KEY_ESC" => "KEY_MUHENKAN",
    "KEY_RIGHTALT" => "KEY_ESC",
    "KEY_RIGHTMETA" => "KEY_RIGHTALT",
)

function remap(code, map)
    for (before, after) in map
        before == after && continue
        println("#$before -> $after")
        println(" KEYBOARD_KEY_" * code[before] * "=" * lowercase(after))
    end
end

main()